#!/bin/bash
# IsoPod - Isolated Ubuntu Desktop for Claude Development
# Usage: ./isopod.sh <command> [options]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_CONF="$SCRIPT_DIR/projects.conf"
ARCH_FILE="$SCRIPT_DIR/.arch"

# Architecture-dependent settings
get_arch() {
    if [[ -f "$ARCH_FILE" ]]; then
        cat "$ARCH_FILE"
    else
        echo "native"
    fi
}

CURRENT_ARCH="$(get_arch)"

if [[ "$CURRENT_ARCH" == "amd64" ]]; then
    COMPOSE_FILE="$SCRIPT_DIR/docker-compose-amd64.yml"
    CONFIG_CHECKSUM_FILE="$SCRIPT_DIR/.config_checksum_amd64"
    SETUP_MARKER_FILE="$SCRIPT_DIR/.setup_amd64"
    CONTAINER_NAME="iso-pod-ubuntu-amd64"
    PORT_DESKTOP=3100
    PORT_SSH=2322
    PORT_RANGE_HOST="10000-10999"
    PORT_RANGE_CONTAINER="8000-8999"
    PORT_NODE=3110
    PORT_FLASK=5110
else
    COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
    CONFIG_CHECKSUM_FILE="$SCRIPT_DIR/.config_checksum"
    SETUP_MARKER_FILE="$SCRIPT_DIR/.setup_native"
    CONTAINER_NAME="iso-pod-ubuntu"
    PORT_DESKTOP=3000
    PORT_SSH=2222
    PORT_RANGE_HOST="9000-9999"
    PORT_RANGE_CONTAINER="8000-8999"
    PORT_NODE=3010
    PORT_FLASK=5010
fi

# Colors
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
RESET='\033[0m'

# --- Compose generation ---

get_config_checksum() {
    if [[ -f "$PROJECTS_CONF" ]]; then
        md5 -q "$PROJECTS_CONF" 2>/dev/null || md5sum "$PROJECTS_CONF" 2>/dev/null | cut -d' ' -f1
    else
        echo ""
    fi
}

get_saved_checksum() {
    if [[ -f "$CONFIG_CHECKSUM_FILE" ]]; then
        cat "$CONFIG_CHECKSUM_FILE"
    else
        echo ""
    fi
}

save_checksum() {
    get_config_checksum > "$CONFIG_CHECKSUM_FILE"
}

conf_changed() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        return 0
    fi
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        return 1
    fi
    local current_checksum saved_checksum
    current_checksum="$(get_config_checksum)"
    saved_checksum="$(get_saved_checksum)"
    [[ "$current_checksum" != "$saved_checksum" ]]
}

# --- Architecture management ---

set_arch() {
    echo "$1" > "$ARCH_FILE"
}

auto_regenerate() {
    if conf_changed; then
        echo -e "${YELLOW}Detected changes in projects.conf, regenerating...${RESET}"
        generate_compose
        # Restart container if running to apply changes
        if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo -e "${YELLOW}Restarting container to apply changes...${RESET}"
            docker compose -f "$COMPOSE_FILE" down
            docker compose -f "$COMPOSE_FILE" up -d
            # Only save checksum after successful rebuild
            save_checksum
            echo -e "${GREEN}Config applied successfully.${RESET}"
        else
            echo -e "${YELLOW}Container not running. Changes will apply on next start.${RESET}"
            echo -e "${YELLOW}Run 'isopod restart' to rebuild with new config.${RESET}"
        fi
    fi
}

generate_compose() {
    echo "Generating $COMPOSE_FILE..."

    # Parse projects first (handles migration if needed)
    parse_projects

    # Architecture-specific suffixes for volumes
    local vol_suffix=""
    if [[ "$CURRENT_ARCH" == "amd64" ]]; then
        vol_suffix="-amd64"
    fi

    cat > "$COMPOSE_FILE" << HEADER
# Auto-generated by isopod.sh - do not edit manually
# Architecture: $CURRENT_ARCH
# Edit projects.conf and run: ./isopod.sh regenerate

services:
  $CONTAINER_NAME:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
HEADER

    # Add platform directive for amd64 (required for Chrome/Selenium on ARM)
    if [[ "$CURRENT_ARCH" == "amd64" ]]; then
        echo "    platform: linux/amd64" >> "$COMPOSE_FILE"
    fi

    cat >> "$COMPOSE_FILE" << PORTS
    container_name: $CONTAINER_NAME
    environment:
      # Unset VIRTUAL_ENV to fix Poetry/pip (lsiopy is read-only)
      # Keep /lsiopy/bin in PATH for selkies desktop service
      - PATH=/config/.local/bin:/config/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/lsiopy/bin
      - VIRTUAL_ENV=
    ports:
      - "${PORT_DESKTOP}:3000"       # Desktop
      - "${PORT_SSH}:22"             # SSH
      - "${PORT_RANGE_HOST}:${PORT_RANGE_CONTAINER}"  # All 8xxx ports
      - "${PORT_NODE}:3001"          # Node.js alternate
      - "${PORT_FLASK}:5000"         # Flask
    volumes:
      - ubuntu-config${vol_suffix}:/config
      - ubuntu-usr${vol_suffix}:/usr
      - ubuntu-opt${vol_suffix}:/opt
      - ubuntu-var${vol_suffix}:/var
      - ubuntu-root${vol_suffix}:/root
      # Browser and IDE configs (explicit volumes for persistence across rebuilds)
      - chrome-config${vol_suffix}:/config/.config/google-chrome
      - chromium-config${vol_suffix}:/config/.config/chromium
      - vscode-config${vol_suffix}:/config/.config/Code
      - vscode-extensions${vol_suffix}:/config/.vscode
      - ./scripts/setup-container.sh:/setup-container.sh:ro
PORTS

    local volume_count=0
    for i in "${!PROJECT_NAMES[@]}"; do
        local name="${PROJECT_NAMES[$i]}"
        local host_path="${PROJECT_HOST_PATHS[$i]}"
        local git="${PROJECT_GIT[$i]}"

        echo "      # Project: $name" >> "$COMPOSE_FILE"
        echo "      - $host_path:/projects/$name" >> "$COMPOSE_FILE"
        if [[ "$git" == "false" ]]; then
            echo "      - git-exclude${vol_suffix}-$volume_count:/projects/$name/.git" >> "$COMPOSE_FILE"
            ((volume_count++))
        fi
    done

    # Screenshots directory (if configured)
    if [[ -n "$SCREENSHOTS_PATH" ]]; then
        echo "      # Screenshots (read-only)" >> "$COMPOSE_FILE"
        echo "      - $SCREENSHOTS_PATH:/screenshots:ro" >> "$COMPOSE_FILE"
    fi

    cat >> "$COMPOSE_FILE" << VOLUMES
    shm_size: "2gb"
    restart: unless-stopped

volumes:
  ubuntu-config${vol_suffix}:
  ubuntu-usr${vol_suffix}:
  ubuntu-opt${vol_suffix}:
  ubuntu-var${vol_suffix}:
  ubuntu-root${vol_suffix}:
  chrome-config${vol_suffix}:
  chromium-config${vol_suffix}:
  vscode-config${vol_suffix}:
  vscode-extensions${vol_suffix}:
VOLUMES

    for ((i=0; i<volume_count; i++)); do
        echo "  git-exclude${vol_suffix}-$i:" >> "$COMPOSE_FILE"
    done

    echo "Generated $COMPOSE_FILE"
}

# --- Container management ---

check_container() {
    # Always check for config changes first
    auto_regenerate

    if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
        echo -e "${YELLOW}Container not running. Starting...${RESET}"
        [[ ! -f "$COMPOSE_FILE" ]] && generate_compose
        docker compose -f "$COMPOSE_FILE" up -d
        echo -n "Waiting for container"
        for i in {1..30}; do
            if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
                echo -e " ${GREEN}ready${RESET}"
                # Auto-run setup if this is a fresh environment
                auto_setup
                return 0
            fi
            echo -n "."
            sleep 1
        done
        echo -e "\n${RED}Error: Container failed to start${RESET}"
        exit 1
    fi

    # Container already running - still check if setup needed
    auto_setup
}

cmd_up() {
    auto_regenerate
    [[ ! -f "$COMPOSE_FILE" ]] && generate_compose
    docker compose -f "$COMPOSE_FILE" up -d
    # Save checksum now that container is up with current config
    save_checksum
    echo ""
    echo -e "${BOLD}Architecture:${RESET} $CURRENT_ARCH"
    echo -e "${BOLD}Container:${RESET}    $CONTAINER_NAME"
    echo -e "${BOLD}Desktop:${RESET}      http://localhost:${PORT_DESKTOP}"
    echo ""
    echo "Run './isopod.sh setup' to install dev tools (first time only)"
}

cmd_restart() {
    echo -e "${YELLOW}Rebuilding container ($CURRENT_ARCH)...${RESET}"
    [[ ! -f "$COMPOSE_FILE" ]] && generate_compose
    # Always regenerate if config exists
    if [[ -f "$PROJECTS_CONF" ]]; then
        generate_compose
    fi
    docker compose -f "$COMPOSE_FILE" down
    docker compose -f "$COMPOSE_FILE" up -d
    # Save checksum after successful rebuild
    save_checksum
    echo -e "${GREEN}Container rebuilt successfully.${RESET}"
    echo ""
    echo -e "${BOLD}Desktop:${RESET} http://localhost:${PORT_DESKTOP}"
}

cmd_down() {
    docker compose -f "$COMPOSE_FILE" down
}

cmd_setup() {
    echo -e "${YELLOW}Installing development tools in container ($CURRENT_ARCH)...${RESET}"
    if docker exec "$CONTAINER_NAME" /setup-container.sh; then
        touch "$SETUP_MARKER_FILE"
        echo -e "${GREEN}Setup complete for $CURRENT_ARCH environment.${RESET}"
    else
        echo -e "${RED}Setup failed.${RESET}"
        return 1
    fi
}

needs_setup() {
    [[ ! -f "$SETUP_MARKER_FILE" ]]
}

auto_setup() {
    if needs_setup; then
        echo -e "${YELLOW}First run for $CURRENT_ARCH environment - running setup...${RESET}"
        cmd_setup
    fi
}

cmd_regenerate() {
    generate_compose
    # Restart container if running to apply changes
    if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
        echo -e "${YELLOW}Restarting container to apply changes...${RESET}"
        docker compose -f "$COMPOSE_FILE" down
        docker compose -f "$COMPOSE_FILE" up -d
        # Save checksum after successful rebuild
        save_checksum
        echo -e "${GREEN}Done.${RESET}"
    else
        echo "Changes will apply when container starts."
        echo "Run 'isopod restart' to rebuild with new config."
    fi
}

cmd_browser() {
    local url="${1:-http://localhost:${PORT_DESKTOP}}"
    echo "Opening $url ($CURRENT_ARCH)..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        open "$url"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        xdg-open "$url" 2>/dev/null || sensible-browser "$url"
    elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
        start "$url"
    else
        echo "Please open $url in your browser"
    fi
}

# --- Config format detection and migration ---

is_old_format() {
    [[ ! -f "$PROJECTS_CONF" ]] && return 1
    # Old format has lines like "/path/to/project:true"
    # TOML format has lines like "[ProjectName]" or "key = value"
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
        # If line starts with [ or contains =, it's TOML
        if [[ "$line" =~ ^\[.*\]$ ]] || [[ "$line" =~ = ]]; then
            return 1
        fi
        # If line matches /path:bool pattern, it's old format
        if [[ "$line" =~ ^/.+:(true|false)$ ]]; then
            return 0
        fi
    done < "$PROJECTS_CONF"
    return 1
}

migrate_config() {
    echo -e "${YELLOW}Migrating projects.conf to TOML format...${RESET}"
    local temp_file="$PROJECTS_CONF.new"

    cat > "$temp_file" << 'EOF'
# IsoPod Project Configuration (TOML format)
#
# Format:
# [ProjectName]
# path = /full/path/to/project
# git = true|false
#
# Example:
# [MyApp]
# path = /Users/someone/projects/MyApp
# git = false

EOF

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
        local path="${line%%:*}"
        local include_git="${line##*:}"
        local folder_name="$(basename "$path")"

        cat >> "$temp_file" << EOF
[$folder_name]
path = $path
git = $include_git

EOF
    done < "$PROJECTS_CONF"

    mv "$PROJECTS_CONF" "$PROJECTS_CONF.old"
    mv "$temp_file" "$PROJECTS_CONF"
    echo -e "${GREEN}Migration complete.${RESET} Old config saved as projects.conf.old"
}

check_and_migrate() {
    if is_old_format; then
        migrate_config
    fi
}

# --- Project detection ---

declare -a PROJECT_NAMES
declare -a PROJECT_PATHS
declare -a PROJECT_GIT
declare -a PROJECT_CHROME
declare -a PROJECT_HOST_PATHS

# Global settings (from [Settings] section)
SCREENSHOTS_PATH=""

parse_projects() {
    PROJECT_NAMES=()
    PROJECT_PATHS=()
    PROJECT_GIT=()
    PROJECT_CHROME=()
    PROJECT_HOST_PATHS=()
    SCREENSHOTS_PATH=""

    [[ ! -f "$PROJECTS_CONF" ]] && return

    # Check and migrate old format
    check_and_migrate

    local idx=0
    local current_section=""
    local current_name=""
    local current_path=""
    local current_git="false"
    local current_chrome="false"

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*#.*$ || -z "${line// }" ]] && continue

        # Section header [ProjectName] or [Settings]
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            # Save previous project if complete (and not Settings)
            if [[ -n "$current_name" && -n "$current_path" && "$current_section" != "Settings" ]]; then
                PROJECT_NAMES[$idx]="$current_name"
                PROJECT_PATHS[$idx]="/projects/$current_name"
                PROJECT_GIT[$idx]="$current_git"
                PROJECT_CHROME[$idx]="$current_chrome"
                PROJECT_HOST_PATHS[$idx]="$current_path"
                ((idx++))
            fi
            current_section="${BASH_REMATCH[1]}"
            current_name="${BASH_REMATCH[1]}"
            current_path=""
            current_git="false"
            current_chrome="false"
            continue
        fi

        # Key = value pairs
        if [[ "$line" =~ ^[[:space:]]*([^=]+)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local value="${BASH_REMATCH[2]}"
            # Trim whitespace
            key="${key%% }"
            key="${key## }"
            value="${value%% }"
            value="${value## }"
            # Expand ~ to $HOME
            value="${value/#\~/$HOME}"

            if [[ "$current_section" == "Settings" ]]; then
                # Global settings
                case "$key" in
                    screenshots) SCREENSHOTS_PATH="$value" ;;
                esac
            else
                # Project settings
                case "$key" in
                    path) current_path="$value" ;;
                    git) current_git="$value" ;;
                    chrome) current_chrome="$value" ;;
                esac
            fi
        fi
    done < "$PROJECTS_CONF"

    # Save last project (if not Settings)
    if [[ -n "$current_name" && -n "$current_path" && "$current_section" != "Settings" ]]; then
        PROJECT_NAMES[$idx]="$current_name"
        PROJECT_PATHS[$idx]="/projects/$current_name"
        PROJECT_GIT[$idx]="$current_git"
        PROJECT_CHROME[$idx]="$current_chrome"
        PROJECT_HOST_PATHS[$idx]="$current_path"
    fi
}

detect_project() {
    local arg="$1"
    local cwd="$(pwd)"
    PROJECT_IDX=-1

    for i in "${!PROJECT_HOST_PATHS[@]}"; do
        local host_path="${PROJECT_HOST_PATHS[$i]}"
        local folder_name="${PROJECT_NAMES[$i]}"
        local container_path="${PROJECT_PATHS[$i]}"

        if [[ -n "$arg" ]]; then
            if [[ "$arg" == "$folder_name" || "$arg" == "$host_path" || "$arg" == "$container_path" ]]; then
                PROJECT_IDX=$i
                return 0
            fi
        elif [[ "$cwd" == "$host_path" || "$cwd" == "$host_path"/* ]]; then
            PROJECT_IDX=$i
            return 0
        fi
    done
    return 1
}

# --- Interactive selection ---

arrow_select() {
    local title="$1"
    shift
    local items=("$@")
    local count=${#items[@]}
    local current=0

    tput civis
    trap 'tput cnorm' RETURN

    while true; do
        tput clear
        echo ""
        echo -e "${BOLD}$title${RESET}"
        echo -e "${CYAN}Use ↑/↓ arrows, Enter to select${RESET}"
        echo ""

        for i in "${!items[@]}"; do
            if [[ $i -eq $current ]]; then
                echo -e "  ${GREEN}▶ ${items[$i]}${RESET}"
            else
                echo -e "    ${items[$i]}"
            fi
        done

        read -rsn1 key
        if [[ "$key" == $'\x1b' ]]; then
            read -rsn2 key
            case "$key" in
                '[A') ((current--)); [[ $current -lt 0 ]] && current=$((count - 1)) ;;
                '[B') ((current++)); [[ $current -ge $count ]] && current=0 ;;
            esac
        elif [[ "$key" == "" ]]; then
            SELECTED_IDX=$current
            tput cnorm
            tput clear
            return
        fi
    done
}

select_project_interactive() {
    if [[ ${#PROJECT_NAMES[@]} -eq 0 ]]; then
        echo -e "${RED}No projects configured.${RESET}"
        echo "Add one with: ./isopod.sh projects:add /path/to/project"
        return 1
    fi

    if [[ ${#PROJECT_NAMES[@]} -eq 1 ]]; then
        PROJECT_IDX=0
        return 0
    fi

    local items=()
    for i in "${!PROJECT_NAMES[@]}"; do
        local git_status chrome_status
        if [[ "${PROJECT_GIT[$i]}" == "true" ]]; then
            git_status="${GREEN}git${RESET}"
        else
            git_status="${YELLOW}no-git${RESET}"
        fi
        if [[ "${PROJECT_CHROME[$i]}" == "true" ]]; then
            chrome_status="${CYAN}chrome${RESET}"
        else
            chrome_status=""
        fi
        local status_str="$git_status"
        [[ -n "$chrome_status" ]] && status_str="$status_str $chrome_status"
        items+=("$(printf "%-25s %s" "${PROJECT_NAMES[$i]}" "$status_str")")
    done

    arrow_select "Select Project" "${items[@]}"
    PROJECT_IDX=$SELECTED_IDX
}

resolve_project() {
    parse_projects
    if detect_project "$1"; then
        return 0
    elif [[ -n "$1" ]]; then
        echo -e "${RED}Error: Project not found: $1${RESET}"
        echo "Run './isopod.sh projects:list' to see configured projects"
        return 1
    else
        select_project_interactive
    fi
}

select_mode() {
    local items=(
        "Normal mode (safe)"
        "${RED}Dangerous mode (--dangerously-skip-permissions)${RESET}"
    )
    arrow_select "Select Launch Mode" "${items[@]}"
    if [[ $SELECTED_IDX -eq 0 ]]; then
        CLAUDE_MODE=""
    else
        CLAUDE_MODE="--dangerously-skip-permissions"
    fi
}

# --- Project management ---

ensure_projects_conf() {
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "Creating projects.conf..."
        cat > "$PROJECTS_CONF" << 'EOF'
# IsoPod Project Configuration (TOML format)
#
# Format:
# [ProjectName]
# path = /full/path/to/project
# git = true|false
# chrome = true|false
#
# Example:
# [MyApp]
# path = /Users/someone/projects/MyApp
# git = false
# chrome = true

EOF
    fi
}

cmd_projects_list() {
    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "No projects.conf found. Add a project with:"
        echo "  isopod projects:add /path/to/project"
        return 0
    fi

    parse_projects

    if [[ ${#PROJECT_NAMES[@]} -eq 0 ]]; then
        echo "No projects configured."
        echo ""
        echo "Add a project with:"
        echo "  isopod projects:add /path/to/project"
        return 0
    fi

    echo "Configured projects:"
    echo ""
    for i in "${!PROJECT_NAMES[@]}"; do
        local name="${PROJECT_NAMES[$i]}"
        local host_path="${PROJECT_HOST_PATHS[$i]}"
        local git="${PROJECT_GIT[$i]}"
        local chrome="${PROJECT_CHROME[$i]}"

        echo "  $name"
        echo "    Path:   $host_path"
        echo "    Git:    $([ "$git" == "true" ] && echo "on" || echo "off")"
        echo "    Chrome: $([ "$chrome" == "true" ] && echo "on" || echo "off")"
        echo ""
    done

    echo "Total: ${#PROJECT_NAMES[@]} project(s)"
}

cmd_projects_add() {
    local path=""
    local include_git=""
    local include_chrome=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --git)
                if [[ "$2" == "true" || "$2" == "false" ]]; then
                    include_git="$2"
                    shift 2
                else
                    echo -e "${RED}Error: --git requires 'true' or 'false'${RESET}"
                    return 1
                fi
                ;;
            --chrome)
                if [[ "$2" == "true" || "$2" == "false" ]]; then
                    include_chrome="$2"
                    shift 2
                else
                    echo -e "${RED}Error: --chrome requires 'true' or 'false'${RESET}"
                    return 1
                fi
                ;;
            -*)
                echo -e "${RED}Error: Unknown option: $1${RESET}"
                return 1
                ;;
            *)
                if [[ -z "$path" ]]; then
                    path="$1"
                else
                    echo -e "${RED}Error: Multiple paths specified${RESET}"
                    return 1
                fi
                shift
                ;;
        esac
    done

    if [[ -z "$path" ]]; then
        echo "Usage: isopod projects:add <path> [--git true|false] [--chrome true|false]"
        echo ""
        echo "Examples:"
        echo "  isopod projects:add ~/projects/MyApp"
        echo "  isopod projects:add ~/projects/MyApp --git true"
        echo "  isopod projects:add ~/projects/MyApp --chrome true"
        echo "  isopod projects:add ~/projects/MyApp --git true --chrome true"
        return 1
    fi

    if [[ ! -d "$path" ]]; then
        echo -e "${RED}Error: Directory does not exist: $path${RESET}"
        return 1
    fi

    path="$(cd "$path" && pwd)"
    folder_name="$(basename "$path")"

    ensure_projects_conf
    check_and_migrate

    # Check if project exists and get current settings
    parse_projects
    local exists=false
    local old_git=""
    local old_chrome=""
    local existing_idx=-1

    for i in "${!PROJECT_NAMES[@]}"; do
        if [[ "${PROJECT_HOST_PATHS[$i]}" == "$path" ]]; then
            exists=true
            old_git="${PROJECT_GIT[$i]}"
            old_chrome="${PROJECT_CHROME[$i]}"
            existing_idx=$i
            break
        fi
    done

    # For new projects, default git=false, chrome=true; for existing, keep current if not specified
    if [[ "$exists" == "true" ]]; then
        [[ -z "$include_git" ]] && include_git="$old_git"
        [[ -z "$include_chrome" ]] && include_chrome="$old_chrome"
    else
        [[ -z "$include_git" ]] && include_git="false"
        [[ -z "$include_chrome" ]] && include_chrome="true"
    fi

    # Rebuild config file in TOML format
    local temp_file="$PROJECTS_CONF.tmp"

    # Write header
    cat > "$temp_file" << 'EOF'
# IsoPod Project Configuration (TOML format)
#
# Format:
# [ProjectName]
# path = /full/path/to/project
# git = true|false
# chrome = true|false
#
# Example:
# [MyApp]
# path = /Users/someone/projects/MyApp
# git = false
# chrome = true

EOF

    # Write existing projects (skip the one being updated)
    for i in "${!PROJECT_NAMES[@]}"; do
        if [[ $i -ne $existing_idx ]]; then
            cat >> "$temp_file" << EOF
[${PROJECT_NAMES[$i]}]
path = ${PROJECT_HOST_PATHS[$i]}
git = ${PROJECT_GIT[$i]}
chrome = ${PROJECT_CHROME[$i]}

EOF
        fi
    done

    # Add the new/updated project
    cat >> "$temp_file" << EOF
[$folder_name]
path = $path
git = $include_git
chrome = $include_chrome

EOF

    mv "$temp_file" "$PROJECTS_CONF"

    # Report changes
    local changes=()
    if [[ "$exists" == "true" ]]; then
        [[ "$old_git" != "$include_git" ]] && changes+=("Git: $([ "$old_git" == "true" ] && echo "on" || echo "off") -> $([ "$include_git" == "true" ] && echo "on" || echo "off")")
        [[ "$old_chrome" != "$include_chrome" ]] && changes+=("Chrome: $([ "$old_chrome" == "true" ] && echo "on" || echo "off") -> $([ "$include_chrome" == "true" ] && echo "on" || echo "off")")

        if [[ ${#changes[@]} -gt 0 ]]; then
            echo -e "${GREEN}Updated project: $folder_name${RESET}"
            for change in "${changes[@]}"; do
                echo "  $change"
            done
        else
            echo -e "${YELLOW}Project unchanged: $folder_name${RESET}"
            echo "  Git: $([ "$include_git" == "true" ] && echo "on" || echo "off"), Chrome: $([ "$include_chrome" == "true" ] && echo "on" || echo "off")"
        fi
    else
        echo -e "${GREEN}Added project: $folder_name${RESET}"
        echo "  Path:   $path"
        echo "  Git:    $([ "$include_git" == "true" ] && echo "on" || echo "off")"
        echo "  Chrome: $([ "$include_chrome" == "true" ] && echo "on" || echo "off")"
    fi
    echo ""
    echo "Changes will auto-apply on next command (claude, bash, code, etc.)"
}

cmd_projects_remove() {
    local target="$1"

    if [[ -z "$target" ]]; then
        echo "Usage: isopod projects:remove <path|name>"
        return 1
    fi

    if [[ ! -f "$PROJECTS_CONF" ]]; then
        echo "Error: No projects.conf found"
        return 1
    fi

    check_and_migrate
    parse_projects

    local found=false
    local found_name=""
    local remove_idx=-1

    for i in "${!PROJECT_NAMES[@]}"; do
        local name="${PROJECT_NAMES[$i]}"
        local host_path="${PROJECT_HOST_PATHS[$i]}"

        if [[ "$host_path" == "$target" || "$name" == "$target" ]]; then
            found=true
            found_name="$name"
            remove_idx=$i
            break
        fi
    done

    if [[ "$found" != "true" ]]; then
        echo -e "${RED}Error: Project not found: $target${RESET}"
        return 1
    fi

    # Rebuild config file without the removed project
    local temp_file="$PROJECTS_CONF.tmp"

    cat > "$temp_file" << 'EOF'
# IsoPod Project Configuration (TOML format)
#
# Format:
# [ProjectName]
# path = /full/path/to/project
# git = true|false
# chrome = true|false
#
# Example:
# [MyApp]
# path = /Users/someone/projects/MyApp
# git = false
# chrome = true

EOF

    for i in "${!PROJECT_NAMES[@]}"; do
        if [[ $i -ne $remove_idx ]]; then
            cat >> "$temp_file" << EOF
[${PROJECT_NAMES[$i]}]
path = ${PROJECT_HOST_PATHS[$i]}
git = ${PROJECT_GIT[$i]}
chrome = ${PROJECT_CHROME[$i]}

EOF
        fi
    done

    mv "$temp_file" "$PROJECTS_CONF"

    echo -e "${GREEN}Removed project: $found_name${RESET}"
    echo ""
    echo "Changes will auto-apply on next command (claude, bash, code, etc.)"
}

# --- Architecture commands ---

cmd_arch() {
    local action="$1"
    local current_arch="$(get_arch)"

    # Check container status
    local native_status amd64_status
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^iso-pod-ubuntu$"; then
        native_status="${GREEN}running${RESET}"
    else
        native_status="${YELLOW}stopped${RESET}"
    fi
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^iso-pod-ubuntu-amd64$"; then
        amd64_status="${GREEN}running${RESET}"
    else
        amd64_status="${YELLOW}stopped${RESET}"
    fi

    case "$action" in
        ""|status)
            echo -e "${BOLD}Active architecture:${RESET} $current_arch"
            echo ""
            echo "Environments (can run in parallel):"
            echo ""
            if [[ "$current_arch" == "native" ]]; then
                echo -e "  ${GREEN}▶ native${RESET} [$native_status]"
            else
                echo -e "    native [$native_status]"
            fi
            echo "      Desktop: http://localhost:3000"
            echo "      SSH:     ssh abc@localhost -p 2222"
            echo "      Ports:   container 8xxx → host 9xxx"
            echo ""
            if [[ "$current_arch" == "amd64" ]]; then
                echo -e "  ${GREEN}▶ amd64${RESET}  [$amd64_status] (x86_64 emulated)"
            else
                echo -e "    amd64  [$amd64_status] (x86_64 emulated)"
            fi
            echo "      Desktop: http://localhost:3100"
            echo "      SSH:     ssh abc@localhost -p 2322"
            echo "      Ports:   container 8xxx → host 10xxx"
            echo ""
            echo "Switch active: isopod arch native|amd64"
            echo "Both can run simultaneously with different ports."
            ;;
        native)
            if [[ "$current_arch" == "native" ]]; then
                echo -e "${YELLOW}Already using native architecture.${RESET}"
                return 0
            fi
            set_arch "native"
            echo -e "${GREEN}Switched to native architecture.${RESET}"
            echo "Desktop: http://localhost:3000"
            ;;
        amd64)
            if [[ "$current_arch" == "amd64" ]]; then
                echo -e "${YELLOW}Already using amd64 architecture.${RESET}"
                return 0
            fi
            set_arch "amd64"
            echo -e "${GREEN}Switched to amd64 architecture.${RESET}"
            echo "Desktop: http://localhost:3100"
            ;;
        *)
            echo -e "${RED}Unknown architecture: $action${RESET}"
            echo "Valid options: native, amd64"
            return 1
            ;;
    esac
}

# --- Main commands ---

cmd_claude() {
    local extra_args=("$@")

    check_container
    parse_projects

    if detect_project ""; then
        echo -e "${GREEN}Detected project: ${BOLD}${PROJECT_NAMES[$PROJECT_IDX]}${RESET}"
    else
        select_project_interactive || exit 1
    fi

    select_mode

    local project_name="${PROJECT_NAMES[$PROJECT_IDX]}"
    local project_path="${PROJECT_PATHS[$PROJECT_IDX]}"
    local project_chrome="${PROJECT_CHROME[$PROJECT_IDX]}"

    tput clear
    echo ""
    echo -e "${GREEN}Launching Claude in ${BOLD}$project_name${RESET}${GREEN}...${RESET}"

    if [[ -n "$CLAUDE_MODE" ]]; then
        echo -e "${YELLOW}Mode: DANGEROUS (skipping permissions)${RESET}"
    else
        echo "Mode: Normal"
    fi

    if [[ "$project_chrome" == "true" ]]; then
        echo -e "${CYAN}Chrome: enabled (configure MCP in Claude settings)${RESET}"
    fi

    if [[ ${#extra_args[@]} -gt 0 ]]; then
        echo "Args: ${extra_args[*]}"
    fi
    echo ""

    local claude_cmd="claude $CLAUDE_MODE ${extra_args[*]}"

    docker exec -it -u abc -e HOME=/config -w "$project_path" "$CONTAINER_NAME" \
        /bin/bash -c "source /etc/profile.d/poetry.sh 2>/dev/null; source ~/.bashrc 2>/dev/null; $claude_cmd"
}

cmd_bash() {
    local project="$1"
    check_container
    if resolve_project "$project"; then
        echo "Connecting to ${PROJECT_NAMES[$PROJECT_IDX]}..."
        docker exec -it -w "${PROJECT_PATHS[$PROJECT_IDX]}" "$CONTAINER_NAME" bash
    else
        [[ -z "$project" ]] && return 1
        exit 1
    fi
}

cmd_code() {
    local project="$1"
    if resolve_project "$project"; then
        echo "Opening VS Code in ${PROJECT_NAMES[$PROJECT_IDX]} ($CURRENT_ARCH)..."
        code --remote ssh-remote+abc@localhost:${PORT_SSH} "${PROJECT_PATHS[$PROJECT_IDX]}"
    else
        [[ -z "$project" ]] && return 1
        exit 1
    fi
}

cmd_windsurf() {
    local project="$1"
    if resolve_project "$project"; then
        echo "Opening Windsurf in ${PROJECT_NAMES[$PROJECT_IDX]} ($CURRENT_ARCH)..."
        windsurf --remote ssh-remote+abc@localhost:${PORT_SSH} "${PROJECT_PATHS[$PROJECT_IDX]}"
    else
        [[ -z "$project" ]] && return 1
        exit 1
    fi
}

cmd_help() {
    cat << HELP
IsoPod - Isolated Ubuntu Desktop for Claude Development

Usage: isopod <command> [options]

Setup alias (copy & paste):
  echo 'alias isopod="$SCRIPT_DIR/isopod.sh"' >> ~/.zshrc && source ~/.zshrc
  echo 'alias isopod="$SCRIPT_DIR/isopod.sh"' >> ~/.bashrc && source ~/.bashrc

Container:
  up              Start the container
  down            Stop the container (data persists)
  restart         Stop and rebuild container with current config
  setup           Install Python, Poetry, Rust, Node, Claude CLI
  regenerate      Rebuild docker-compose.yml from projects.conf
  browser [url]   Open browser (default: desktop for active arch)

Development:
  bash [project]      Bash shell in project directory
  code [project]      VS Code remote to project
  windsurf [project]  Windsurf remote to project
  claude [args]       Launch Claude CLI (auto-detects project, asks mode)

Project Management:
  projects:list       List configured projects
  projects:add        Add a project mount
  projects:remove     Remove a project mount

Architecture (both can run in parallel):
  arch                Show status of both environments
  arch native         Switch to native (faster, default)
  arch amd64          Switch to amd64 (x86_64 emulated)

Port Mappings:
                    Native    AMD64
  Desktop           3000      3100
  SSH               2222      2322
  8xxx range        9xxx      10xxx
  Node.js (3001)    3010      3110
  Flask (5000)      5010      5110

Note: bash/code/windsurf/claude auto-detect project from current directory.

Examples:
  isopod up                    # Start container
  isopod browser               # Open desktop in browser
  isopod setup                 # Install dev tools
  isopod claude                # Launch Claude (auto-detect + mode picker)
  isopod claude --resume       # Resume previous session
  isopod bash                  # Bash shell
  isopod code MyApp            # VS Code in specific project

  isopod projects:add ~/projects/MyApp
  isopod projects:add ~/projects/MyApp --git true      # Enable git
  isopod projects:add ~/projects/MyApp --chrome true   # Enable Chrome MCP
  isopod projects:add ~/projects/MyApp --git true --chrome true

  isopod arch                 # Show current architecture
  isopod arch amd64           # Switch to amd64 (x86_64 emulated)
  isopod arch native          # Switch back to native (faster)
HELP
}

# Main
case "${1:-}" in
    up) cmd_up ;;
    down) cmd_down ;;
    restart) cmd_restart ;;
    setup) cmd_setup ;;
    regenerate) cmd_regenerate ;;
    browser|open) cmd_browser "$2" ;;
    bash) cmd_bash "$2" ;;
    code) cmd_code "$2" ;;
    windsurf) cmd_windsurf "$2" ;;
    claude) shift; cmd_claude "$@" ;;
    projects:list) cmd_projects_list ;;
    projects:add) shift; cmd_projects_add "$@" ;;
    projects:remove) cmd_projects_remove "$2" ;;
    arch) cmd_arch "$2" ;;
    help|--help|-h) cmd_help ;;
    "")
        echo -e "${CYAN}Tip: Run 'isopod --help' for all commands${RESET}"
        echo ""
        cmd_claude
        ;;
    *) echo "Unknown command: $1"; cmd_help; exit 1 ;;
esac
